---
units: units.tsv
sample: samples.tsv

# files and directories
working_dir: "temp/"
result_dir: "results/"
sample_dir: "/exports/humgen/jihed/rrbs_zbtb24/fastq/"
genome_dir: "/exports/humgen/jihed/rrbs_zbtb24/reference"
